name: Java Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3307
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'image_classification'
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          mysql user: 'root'
          mysql password: 'root'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action/@v2

      - name: Init gradle
        run: | 
          cd Image-Classification 
          ./gradlew init

      - name: Execute Gradle build
        run: |
          cd Image-Classification
          ./gradlew build -x test

      - name: Start Spring application
        run: |
          java -jar Image-Classification/build/libs/Image-Classification-0.0.1-SNAPSHOT.jar &
          sleep 10

      - name: Run tests
        run: |
          cd Image-Classification
          ./gradlew test

      - name: Stop Spring application
        run: |
          pkill -f 'Image-Classification-0.0.1-SNAPSHOT.jar'
