name: Java Build project

on:
  push:
    branches:
      - '*'

jobs:
  build-with-tests:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Init gradle
        run: | 
          cd Image-Classification 
          ./gradlew init
        
      - name: Execute Gradle build
        run: |
          cd Image-Classification
          ./gradlew build -x test
      
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: Image-Classification/build/reports/